apiVersion: v1
kind: Service
metadata:
  name: meditracker-app
  namespace: meditracker
  labels:
    app: meditracker
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5000"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: meditracker
  ports:
  - port: 5000
    targetPort: 5000
    name: http
  type: ClusterIP